In [1]:
import anndata as ad
import pandas as pd
import numpy as np
import os

In [2]:
adata = ad.read_h5ad("/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/adatas/cells_annotated_pp_osteocytes_cleaned.h5ad")
path = "/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/artifact_bone_masks/regionprops"

In [3]:
df = pd.read_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/regionprops/TS-373_IMC07_UB_001.csv')

In [4]:
dfs = []
for file in os.listdir(path):
    if file.endswith('.csv') and 'IMC' in file:
        df = pd.read_csv(os.path.join(path, file))
        df['image_ID'] = file
        dfs.append(df)
df = pd.concat(dfs, axis=0)

In [5]:
df

,Object,area,centroid-0,centroid-1,axis_major_length,axis_minor_length,eccentricity,distance_to_bone,distance_to_bone_corrected,image_ID,is_artifact
0,1,11,0.454545,285.727273,6.410748,1.964940,0.951868,580.181006,567.073188,TS-373_IMC04_MGUS_002.csv,NaN
1,2,14,1.071429,670.214286,5.055352,3.843169,0.649668,445.468293,376.151565,TS-373_IMC04_MGUS_002.csv,NaN
2,3,19,0.947368,310.315789,7.359593,3.274572,0.895561,568.465478,552.521493,TS-373_IMC04_MGUS_002.csv,NaN
3,4,9,0.444444,679.222222,5.274258,1.946056,0.929440,440.454311,372.786802,TS-373_IMC04_MGUS_002.csv,NaN
4,5,167,4.389222,223.676647,20.000172,12.000670,0.799979,606.970345,595.218447,TS-373_IMC04_MGUS_002.csv,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8334,8335,4,998.500000,770.500000,2.000000,2.000000,0.000000,532.430277,527.754678,TS-373_IMC66_B_002.csv,NaN
8335,8336,25,997.880000,806.200000,10.216817,3.350558,0.944697,531.008475,526.046576,TS-373_IMC66_B_002.csv,NaN
8336,8337,30,997.933333,862.166667,10.704425,3.665114,0.939557,533.638454,528.277389,TS-373_IMC66_B_002.csv,NaN
8337,8338,14,998.071429,547.857143,5.449354,3.145851,0.816540,589.512510,580.112058,TS-373_IMC66_B_002.csv,NaN
8338,8339,18,998.166667,721.111111,7.416722,3.039597,0.912162,538.242510,533.985019,TS-373_IMC66_B_002.csv,NaN

In [6]:
df.index = 'Object ' + df['Object'].astype(str) + ' in ' + df['image_ID']
df.drop(columns=['is_artifact'], inplace=True)
df = df[df['area'] >= 4]

In [7]:
adata.obs

,Object,area,Y_centroid,X_centroid,axis_major_length,axis_minor_length,eccentricity,distance_to_bone,Phenotype,image_ID,disease,patient_ID,ROI,disease2,Phenotype2
Object 1 in TS-373_IMC77_B_001.csv,1,16,0.562500,801.750000,8.430760,2.420699,0.957893,26.019224,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown
Object 2 in TS-373_IMC77_B_001.csv,2,12,0.833333,859.583333,5.176698,2.940449,0.823017,84.005952,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown
Object 3 in TS-373_IMC77_B_001.csv,3,13,0.846154,34.000000,5.203549,3.076923,0.806443,123.405835,Neutrophils,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Neutrophils
Object 4 in TS-373_IMC77_B_001.csv,4,9,1.000000,42.000000,3.265986,3.265986,0.000000,118.713942,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown
Object 5 in TS-373_IMC77_B_001.csv,5,23,1.478261,57.565217,8.151264,3.901335,0.878024,110.476242,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Object 6622 in TS-373_IMC83_B_001.csv,6622,11,998.000000,883.545455,4.077022,3.677860,0.431538,250.503493,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils
Object 6623 in TS-373_IMC83_B_001.csv,6623,27,997.407407,978.703704,7.171071,5.069573,0.707266,327.273586,CD4+Tcells,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,CD4+Tcells
Object 6624 in TS-373_IMC83_B_001.csv,6624,25,997.640000,996.320000,7.554137,4.235920,0.827991,342.067245,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils
Object 6625 in TS-373_IMC83_B_001.csv,6625,13,997.692308,820.153846,5.547002,3.412473,0.788377,195.256242,activated Macrophages/Monocytes,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,activated Macrophages/Monocytes
Object 6626 in TS-373_IMC83_B_001.csv,6626,15,997.600000,907.600000,4.618802,4.026578,0.489898,269.696125,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils

In [8]:
adata.obs.isna().sum()

Object                    0
area                      0
Y_centroid                0
X_centroid                0
axis_major_length         0
axis_minor_length         0
eccentricity              0
distance_to_bone     150026
Phenotype                 0
image_ID                  0
disease                   0
patient_ID                0
ROI                       0
disease2                  0
Phenotype2                0
dtype: int64

In [9]:
df['distance_to_bone_corrected']

Object 1 in TS-373_IMC04_MGUS_002.csv    567.073188
Object 2 in TS-373_IMC04_MGUS_002.csv    376.151565
Object 3 in TS-373_IMC04_MGUS_002.csv    552.521493
Object 4 in TS-373_IMC04_MGUS_002.csv    372.786802
Object 5 in TS-373_IMC04_MGUS_002.csv    595.218447
                                            ...
Object 8335 in TS-373_IMC66_B_002.csv    527.754678
Object 8336 in TS-373_IMC66_B_002.csv    526.046576
Object 8337 in TS-373_IMC66_B_002.csv    528.277389
Object 8338 in TS-373_IMC66_B_002.csv    580.112058
Object 8339 in TS-373_IMC66_B_002.csv    533.985019
Name: distance_to_bone_corrected, Length: 195099, dtype: float64

In [10]:
adata.obs['distance_to_bone_corrected'] = adata.obs['distance_to_bone']

In [11]:

adata.obs['distance_to_bone_corrected'].update(df['distance_to_bone_corrected'])

/var/folders/ry/jl4ll0zx1l709rh4r7_0cq6r0000gn/T/ipykernel_60163/1044832760.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  adata.obs['distance_to_bone_corrected'].update(df['distance_to_bone_corrected'])

In [12]:
adata.obs

,Object,area,Y_centroid,X_centroid,axis_major_length,axis_minor_length,eccentricity,distance_to_bone,Phenotype,image_ID,disease,patient_ID,ROI,disease2,Phenotype2,distance_to_bone_corrected
Object 1 in TS-373_IMC77_B_001.csv,1,16,0.562500,801.750000,8.430760,2.420699,0.957893,26.019224,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown,26.019224
Object 2 in TS-373_IMC77_B_001.csv,2,12,0.833333,859.583333,5.176698,2.940449,0.823017,84.005952,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown,84.005952
Object 3 in TS-373_IMC77_B_001.csv,3,13,0.846154,34.000000,5.203549,3.076923,0.806443,123.405835,Neutrophils,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Neutrophils,123.405835
Object 4 in TS-373_IMC77_B_001.csv,4,9,1.000000,42.000000,3.265986,3.265986,0.000000,118.713942,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown,118.713942
Object 5 in TS-373_IMC77_B_001.csv,5,23,1.478261,57.565217,8.151264,3.901335,0.878024,110.476242,Unknown,TS-373_IMC77_B_001.csv,MM_BD,IMC77,001,MM_BD,Unknown,110.476242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Object 6622 in TS-373_IMC83_B_001.csv,6622,11,998.000000,883.545455,4.077022,3.677860,0.431538,250.503493,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils,250.503493
Object 6623 in TS-373_IMC83_B_001.csv,6623,27,997.407407,978.703704,7.171071,5.069573,0.707266,327.273586,CD4+Tcells,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,CD4+Tcells,327.273586
Object 6624 in TS-373_IMC83_B_001.csv,6624,25,997.640000,996.320000,7.554137,4.235920,0.827991,342.067245,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils,342.067245
Object 6625 in TS-373_IMC83_B_001.csv,6625,13,997.692308,820.153846,5.547002,3.412473,0.788377,195.256242,activated Macrophages/Monocytes,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,activated Macrophages/Monocytes,195.256242
Object 6626 in TS-373_IMC83_B_001.csv,6626,15,997.600000,907.600000,4.618802,4.026578,0.489898,269.696125,Neutrophils,TS-373_IMC83_B_001.csv,MM_BD,IMC83,001,MM_BD,Neutrophils,269.696125

In [13]:
adata[adata.obs['image_ID'] == 'TS-373_IMC12_UB_001.csv'].obs

,Object,area,Y_centroid,X_centroid,axis_major_length,axis_minor_length,eccentricity,distance_to_bone,Phenotype,image_ID,disease,patient_ID,ROI,disease2,Phenotype2,distance_to_bone_corrected
Object 1 in TS-373_IMC12_UB_001.csv,1,12,0.666667,202.500000,5.537749,2.981424,0.842701,593.304306,Unknown,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Unknown,594.357636
Object 2 in TS-373_IMC12_UB_001.csv,2,11,0.727273,497.909091,4.966531,2.986694,0.798975,367.695526,Neutrophils,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Neutrophils,367.821968
Object 3 in TS-373_IMC12_UB_001.csv,3,18,1.000000,568.166667,7.136435,3.155976,0.896900,320.140594,Neutrophils,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Neutrophils,318.064459
Object 4 in TS-373_IMC12_UB_001.csv,4,10,0.800000,836.300000,4.541385,2.774134,0.791741,122.641755,Dendritic Cells,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Dendritic Cells,109.018347
Object 5 in TS-373_IMC12_UB_001.csv,5,22,0.909091,845.227273,8.793666,3.116532,0.935091,115.420969,CD68+,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,CD68+,101.828287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Object 6789 in TS-373_IMC12_UB_001.csv,6789,18,998.388889,312.444444,10.177633,2.345680,0.973078,337.960057,Neutrophils,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Neutrophils,338.657644
Object 6790 in TS-373_IMC12_UB_001.csv,6790,16,998.062500,442.187500,6.222716,3.263864,0.851406,276.088754,Neutrophils,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Neutrophils,274.169656
Object 6791 in TS-373_IMC12_UB_001.csv,6791,26,997.961538,585.153846,10.030794,3.219536,0.947091,267.525700,Plasma Cells/MM cells,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Plasma Cells/MM cells,253.031619
Object 6792 in TS-373_IMC12_UB_001.csv,6792,29,998.034483,769.655172,11.182648,3.225859,0.957489,285.334891,Plasma Cells/MM cells,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Plasma Cells/MM cells,218.359795
Object 6793 in TS-373_IMC12_UB_001.csv,6793,12,997.916667,934.666667,4.364045,3.521300,0.590703,212.551170,Unknown,TS-373_IMC12_UB_001.csv,MM_noBD,IMC12,001,MM_noBD,Unknown,121.264174

In [14]:
adata.obs.isna().sum()

Object                             0
area                               0
Y_centroid                         0
X_centroid                         0
axis_major_length                  0
axis_minor_length                  0
eccentricity                       0
distance_to_bone              150026
Phenotype                          0
image_ID                           0
disease                            0
patient_ID                         0
ROI                                0
disease2                           0
Phenotype2                         0
distance_to_bone_corrected    150026
dtype: int64

In [15]:
adata.write_h5ad("/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/adatas/cells_annotated_pp_osteocytes_cleaned.h5ad")

In [16]:
adata

AnnData object with n_obs Ã— n_vars = 1044314 Ã— 33
    obs: 'Object', 'area', 'Y_centroid', 'X_centroid', 'axis_major_length', 'axis_minor_length', 'eccentricity', 'distance_to_bone', 'Phenotype', 'image_ID', 'disease', 'patient_ID', 'ROI', 'disease2', 'Phenotype2', 'distance_to_bone_corrected'
    var: 'name', 'channel', 'deepcell'